"""baseline schema

Revision ID: 003c00bcaa4d
Revises:
Create Date: 2026-04-26 17:48:30.920092

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "003c00bcaa4d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "pay_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("expected_income", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("actual_income", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "additional_income", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "additional_income_description", sa.String(length=200), nullable=True
        ),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_pay_periods_dates", "pay_periods", ["start_date", "end_date"], unique=False
    )
    op.create_table(
        "bill_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("default_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("due_day_of_month", sa.Integer(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spending_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pay_period_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("spent_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["pay_period_id"], ["pay_periods.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_spending_entries_category",
        "spending_entries",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "idx_spending_entries_date", "spending_entries", ["spent_date"], unique=False
    )
    op.create_index(
        "idx_spending_entries_pay_period",
        "spending_entries",
        ["pay_period_id"],
        unique=False,
    )
    op.create_table(
        "pay_period_bills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pay_period_id", sa.Integer(), nullable=False),
        sa.Column("bill_template_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_template_id"], ["bill_templates.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["pay_period_id"], ["pay_periods.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_pay_period_bills_due_date", "pay_period_bills", ["due_date"], unique=False
    )
    op.create_index(
        "idx_pay_period_bills_pay_period",
        "pay_period_bills",
        ["pay_period_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_pay_period_bills_pay_period", table_name="pay_period_bills")
    op.drop_index("idx_pay_period_bills_due_date", table_name="pay_period_bills")
    op.drop_table("pay_period_bills")
    op.drop_index("idx_spending_entries_pay_period", table_name="spending_entries")
    op.drop_index("idx_spending_entries_date", table_name="spending_entries")
    op.drop_index("idx_spending_entries_category", table_name="spending_entries")
    op.drop_table("spending_entries")
    op.drop_table("bill_templates")
    op.drop_index("idx_pay_periods_dates", table_name="pay_periods")
    op.drop_table("pay_periods")
    op.drop_table("categories")
    # ### end Alembic commands ###
