"""add monthly_target to categories

Revision ID: ee271444751b
Revises: 003c00bcaa4d
Create Date: 2026-04-26 21:03:22.235703

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee271444751b"
down_revision: str | Sequence[str] | None = "003c00bcaa4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("monthly_target", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "monthly_target")
    # ### end Alembic commands ###
